Fatih/more explicit tests
maxmind/minfraud-api-node pull request #539
Opened 2022-02-07 21:25 UTC by aktasfatih

PT ID: #177734507

I have changed the tests to show the checks for the camelCase keys.

2022-02-07 23:02 UTC, horgh requested changes
Looks good! Some minor comments.

2022-02-08 16:50 UTC, aktasfatih commented on src/webServiceClient.spec.ts
> +import { Insights } from '@maxmind/geoip2-node';
I have removed that too.

2022-02-08 17:06 UTC, aktasfatih commented on src/webServiceClient.spec.ts
> +      // Note: Couldn't write a check for the default item in the subscores array
It was showing up in the debugger. But, it doesn't anymore😅. I have removed that too.

2022-02-08 17:07 UTC, aktasfatih commented on src/webServiceClient.spec.ts
> +    `('handles missing response $property', async ({ property }) => {
You are right. I have added the tests for those cases.

2022-02-08 17:50 UTC, horgh approved these changes

2022-02-08 17:53 UTC, merged